apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: goldobinaoi/hw2_2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PGHOST
            value: db
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: "postgres"
          - name: PGPASSWORD
            value: "postgrespostgres"
          - name: PGDATABASE
            value: "postgres"
        ports:
        - containerPort: 3000
